### ISSUE TITLE
two dropdowns collides in the same form

### ISSUE THREAD

**Issue by hakushakusama** [pytesNET/tail.select#78]
I am very happy of the work done here, good continuation,
but  i have a issue, when two dropdown select are in the same form when  i open the above one it open on the other, but dont cover it, (i know i am so bad in english, i will try to put image)
Image one  show the  dropdown select button when its collapsed
![66713890_466408270576523_1933253415169687552_n](https://user-images.githubusercontent.com/35413979/60878814-c77d6000-a240-11e9-9fa6-247eceeea0b0.png)

and here when it dropdowned  you will see that  it does collide  with the other one, please any solution did i do something wrong with setups or options,

![66209562_384986858818370_1644699975872937984_n](https://user-images.githubusercontent.com/35413979/60879008-1dea9e80-a241-11e9-9cfa-5f59a1dc2957.png)

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue and I'm really glad that you like it! :D 

This issue has been fixed with #74 by @Calak, please try out the [latest master branch](https://github.com/pytesNET/tail.select/zipball/master). 

Sincerely,
Sam.

**Comment by Calak** [comment]
Yeah, try the last master branch and come back to tell us if it's good.

(and @hakushakusama, for info, you forgot an "i" in "Modifier" :))

**Comment by hakushakusama** [comment]
@SamBrishes  thank you for the quick answer  , but i ave installed my tail.branch through npm, i was thinking its the last version but i did try the referenced  version that you linked up to me, unfortunate nothing changed, i read in the #74 that i depend on a "*.less" file that you must integrate but i don't know how.
i would like really to see how do they fixed the issue.
i will drop some images to show what i did intregrate in my project all the library.
 
![392](https://user-images.githubusercontent.com/35413979/60891784-4765f300-a25e-11e9-954e-01b76867eaa1.png)

i have added two  files :
  - tail.select-full.js.
  - default/tail.select-light-feather.min.css.

Do i need more  then that in my page to make it work.??

**Comment by Calak** [comment]
I don't know why, even with @latest, NPM don't provide the latest version. Maybe because last commit didn't bump the version number? 
So, you have 3 way to fix it:
- Get directly the [css compiled file](https://github.com/pytesNET/tail.select/tree/master/css/default) from the master branch.
- In your css file, search for "`z-index:20`" (you should get ony one match) and replace by "`z-index:28`"
- Wait tonight that he update the version

**Comment by hakushakusama** [comment]
@Calak, i really apreciate your answer,  thank you also for the note i will change that orthographe mistake.
I will do option number 2 i will choose and modify it, and i will tell you.

**Comment by hakushakusama** [comment]
@Calak i did the modification that you suggested to me, i found the value at line 274
![Capture3](https://user-images.githubusercontent.com/35413979/60899981-bb5ac800-a26b-11e9-8798-27d238a98746.PNG)
i changed from 20 to 28 as you recommanded but the issue still there :(, 
this is a screen with browser inspections maybe it will help to see further the issue
![Capture2](https://user-images.githubusercontent.com/35413979/60900258-2dcba800-a26c-11e9-8acc-2e680034864f.PNG)

**Comment by SamBrishes** [comment]
Hellow,

@hakushakusama: I guess you changed the `z-index` value in `css/default/tail.select-light-feather.css` and not in `css/default/tail.select-light-feather.min.css` (so the **`min.css`** file, which you're embedding in the image), or?

Just download [this file](https://github.com/pytesNET/tail.select/blob/master/css/default/tail.select-light-feather.min.css) directly and replace it with your `tail.select-light-feather.min.css` version. :D 

Thanks.

Sincerely,
Sam.

**Comment by Calak** [comment]
@SamBrishes as I said on my previous post.

@hakushakusama Sam explained why your edit didn't fixed your issue, you don't have edited the right file. In your page you use "_tail.select-light-feater**.min**.css_" but in your last screen, you show that you edited "_tail.select-light-feater.css_" (without **.min**, so you edited the un-minified version).

HS: @SamBrishes a double issue + fixes coming soon about the dropdown

**Comment by SamBrishes** [comment]
@hakushakusama You can also wait until @Calak has published his PR, and I'm able to update the npm / GitHub package to 0.5.15. This will definitely solve your issue as well :D

**Comment by hakushakusama** [comment]
@Calak so you did noticed that i changed  the css/default/tail.select-light-feather.css, but i did changed  my includes also like this 
![Capture4](https://user-images.githubusercontent.com/35413979/60910991-6d04f380-a282-11e9-8daa-ce92979b36a7.PNG)
i have download the file that you give me and it works dude thank you so much dude for the help, hopefully you will get  what you desire in your life, i am really happy thanks a lots

**Comment by Calak** [comment]
@SamBrishes My two fixes aren't so trivial that I thought. Spoiler: the 1rst one is about dropdown-inner that overflow the dropdown content, the 2nd is about scroll calculation that can be inconsistent when you use arrow keys.
I hope that my PR will be ready for tomorrow.
